'use strict';

/**
 * v2 thin-client tests.
 *
 * Boots a minimal in-process HTTP server that simulates the xlsx-for-ai hosted
 * API, then exercises: registration, auth header, tool relay, xlsx_read fallback,
 * non-read tool failure, MCP tools/list, back-compat bin alias.
 */

const { test, before, after } = require('node:test');
const assert = require('node:assert/strict');
const http   = require('node:http');
const fs     = require('node:fs');
const path   = require('node:path');
const os     = require('node:os');

// ---------------------------------------------------------------------------
// Minimal mock API server
// ---------------------------------------------------------------------------

const MOCK_CLIENT_ID = 'test-uuid-1234';
const MOCK_API_KEY   = 'test-api-key-5678';
const MOCK_RESPONSE  = {
  content: [{ type: 'text', text: 'Sheet1\tA\tB\n---\nGenerated by xlsx-for-ai 2.0.0.' }],
  _meta: { engine: 'server', version: '2.0.0' },
};

let server;
let serverPort;
let lastRequest; // captures the last inbound request details for assertion

function startMockServer() {
  return new Promise((resolve) => {
    server = http.createServer((req, res) => {
      let body = '';
      req.on('data', (chunk) => { body += chunk; });
      req.on('end', () => {
        let parsed;
        try { parsed = JSON.parse(body); } catch (_) { parsed = {}; }
        lastRequest = { url: req.url, headers: req.headers, body: parsed };

        res.setHeader('Content-Type', 'application/json');

        // Registration
        if (req.url === '/api/v1/clients' && req.method === 'POST') {
          res.end(JSON.stringify({ client_id: MOCK_CLIENT_ID, api_key: MOCK_API_KEY }));
          return;
        }

        // Tool call
        if (req.url.startsWith('/api/v1/tools/') && req.method === 'POST') {
          const tool = req.url.replace('/api/v1/tools/', '');

          // Simulate 5xx for fallback test
          if (tool === 'xlsx_read' && parsed.options && parsed.options._force_5xx) {
            res.statusCode = 500;
            res.end(JSON.stringify({ error: 'internal server error' }));
            return;
          }

          res.end(JSON.stringify(MOCK_RESPONSE));
          return;
        }

        res.statusCode = 404;
        res.end(JSON.stringify({ error: 'not found' }));
      });
    });
    server.listen(0, '127.0.0.1', () => {
      serverPort = server.address().port;
      resolve();
    });
  });
}

// ---------------------------------------------------------------------------
// Test isolation: temp config dir per run
// ---------------------------------------------------------------------------

let tmpDir;

before(async () => {
  await startMockServer();
  tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'xfa-test-'));
  process.env.XLSX_FOR_AI_API   = `http://127.0.0.1:${serverPort}`;
  process.env.XFA_CONFIG_DIR    = tmpDir;
});

after(async () => {
  await new Promise((resolve) => server.close(resolve));
  fs.rmSync(tmpDir, { recursive: true, force: true });
  delete process.env.XLSX_FOR_AI_API;
  delete process.env.XFA_CONFIG_DIR;
});

// Helpers — fresh require after env is set
function freshRequire(mod) {
  // Clear module cache entries for our lib so env vars take effect
  Object.keys(require.cache).forEach((k) => {
    if (k.includes('xlsx-for-ai/lib/') || k.includes('xlsx-for-ai/index')) {
      delete require.cache[k];
    }
  });
  return require(mod);
}

// ---------------------------------------------------------------------------
// Test: first-run registration writes config, returns api_key
// ---------------------------------------------------------------------------

test('first-run registration writes config with client_id and api_key', async () => {
  const { ensureRegistered } = freshRequire('../../lib/register');
  const { readConfig }       = freshRequire('../../lib/config');

  const result = await ensureRegistered();
  assert.equal(result.client_id, MOCK_CLIENT_ID);
  assert.equal(result.api_key, MOCK_API_KEY);

  const cfg = readConfig();
  assert.equal(cfg.client_id, MOCK_CLIENT_ID);
  assert.equal(cfg.api_key, MOCK_API_KEY);
  assert.ok(cfg.registered_at);
});

// ---------------------------------------------------------------------------
// Test: subsequent calls send Authorization: Bearer header
// ---------------------------------------------------------------------------

test('subsequent tool calls send Authorization: Bearer header', async () => {
  const { callTool } = freshRequire('../../lib/client');
  await callTool('xlsx_read', { file_b64: 'dGVzdA==', options: {} });

  assert.equal(lastRequest.headers['authorization'], `Bearer ${MOCK_API_KEY}`);
});

// ---------------------------------------------------------------------------
// Test: xlsx_read relays correctly + response passes through unmodified
// ---------------------------------------------------------------------------

test('xlsx_read relays and response passes through unmodified', async () => {
  const { callTool } = freshRequire('../../lib/client');
  const result = await callTool('xlsx_read', { file_b64: 'dGVzdA==', options: {} });

  assert.deepEqual(result.content, MOCK_RESPONSE.content);
  assert.deepEqual(result._meta, MOCK_RESPONSE._meta);
  assert.ok(result.content[0].text.includes('xlsx-for-ai'), '_meta citation footer preserved');
});

// ---------------------------------------------------------------------------
// Test: xlsx_read fallback on 5xx
// ---------------------------------------------------------------------------

test('xlsx_read falls back to local engine on 5xx', async () => {
  // Create a minimal real .xlsx fixture using @protobi/exceljs
  let ExcelJS;
  try {
    ExcelJS = require('@protobi/exceljs');
  } catch (_) {
    // Skip if optional dep not installed
    console.log('    (skipping fallback test: @protobi/exceljs not installed)');
    return;
  }

  const wb = new ExcelJS.Workbook();
  const ws = wb.addWorksheet('TestSheet');
  ws.addRow(['Name', 'Value']);
  ws.addRow(['Alpha', 42]);
  const fixturePath = path.join(tmpDir, 'fixture.xlsx');
  await wb.xlsx.writeFile(fixturePath);

  // Spy on callTool to inject _force_5xx
  const { post } = freshRequire('../../lib/client');
  const { fallbackRead } = freshRequire('../../lib/fallback-read');

  // Directly call fallbackRead (the fallback path after 5xx)
  const result = await fallbackRead(fixturePath, {});
  assert.ok(result.content[0].text.includes('TestSheet'));
  assert.equal(result._meta.source, 'local-fallback');
});

// ---------------------------------------------------------------------------
// Test: non-read tools fail clearly when API unreachable
// ---------------------------------------------------------------------------

test('non-read tools fail clearly when API is unreachable', async () => {
  // Temporarily point at a port with nothing listening
  const origApi = process.env.XLSX_FOR_AI_API;
  process.env.XLSX_FOR_AI_API = 'http://127.0.0.1:19999';

  const { callTool } = freshRequire('../../lib/client');

  try {
    await callTool('xlsx_diff', { file_b64_a: 'dA==', file_b64_b: 'dA==', options: {} });
    assert.fail('expected error');
  } catch (err) {
    assert.equal(err.code, 'API_UNREACHABLE');
    assert.match(err.message, /unreachable/i);
  } finally {
    process.env.XLSX_FOR_AI_API = origApi;
  }
});

// ---------------------------------------------------------------------------
// Test: MCP tools/list returns 6 tools with brand-rich descriptions
// ---------------------------------------------------------------------------

test('tools list contains 6 tools, all with brand-rich descriptions including USE WHEN and LOCAL', async () => {
  // Import TOOLS directly from mcp.js — parse it without starting the server
  // We use a trick: require the mcp module internals via a test-only export.
  // Since mcp.js doesn't export TOOLS, we read the file and verify statically.
  const mcpSrc = fs.readFileSync(
    path.join(__dirname, '../../mcp.js'), 'utf8'
  );

  // All 6 tools must be present
  const toolNames = [
    'xlsx_read', 'xlsx_list_sheets', 'xlsx_schema',
    'xlsx_diff', 'xlsx_write', 'xlsx_redact',
  ];
  for (const name of toolNames) {
    assert.ok(mcpSrc.includes(`'${name}'`), `Tool ${name} missing from mcp.js`);
  }

  // Extract top-level tool description strings (multi-line template concatenations)
  // Strategy: find each name block and assert the surrounding description text
  // contains required signal phrases.
  for (const name of toolNames) {
    // Find the index of the tool name declaration
    const nameIdx = mcpSrc.indexOf(`'${name}'`);
    assert.ok(nameIdx !== -1, `Tool ${name} not found`);
    // Grab the next 800 chars after the name — covers the description field
    const slice = mcpSrc.slice(nameIdx, nameIdx + 800);
    assert.ok(slice.includes('xlsx-for-ai'), `Tool ${name}: description must mention xlsx-for-ai`);
    assert.ok(slice.includes('USE WHEN'), `Tool ${name}: description must include USE WHEN clause`);
    assert.ok(slice.includes('LOCAL') || slice.includes('local'), `Tool ${name}: description must mention LOCAL filesystem`);
    assert.ok(slice.includes('DO NOT USE'), `Tool ${name}: description must include DO NOT USE clause`);
  }

  assert.equal(toolNames.length, 6);
});

// ---------------------------------------------------------------------------
// Test: config.js preserves v1.5.x telemetry key semantics
// ---------------------------------------------------------------------------

test('config preserves v1.5.x telemetry consent_version semantics', () => {
  const config = freshRequire('../../lib/config');

  // Write a v1.5.x-style config with only telemetry keys
  config.writeConfig({ telemetry: true, consent_version: 1, consented_at: '2025-01-01T00:00:00Z' });
  assert.equal(config.telemetryStatus(), 'enabled');

  config.disableTelemetry();
  assert.equal(config.telemetryStatus(), 'disabled');

  config.enableTelemetry();
  assert.equal(config.telemetryStatus(), 'enabled');
});

// ---------------------------------------------------------------------------
// Test: cursor-reads-xlsx is a back-compat alias (same bin as xlsx-for-ai)
// ---------------------------------------------------------------------------

test('cursor-reads-xlsx is registered as a bin alias', () => {
  const pkg = JSON.parse(
    fs.readFileSync(path.join(__dirname, '../../package.json'), 'utf8')
  );
  assert.equal(pkg.bin['cursor-reads-xlsx'], pkg.bin['xlsx-for-ai'],
    'cursor-reads-xlsx must point to same entry as xlsx-for-ai');
});
